* Notes
 - The username passed to the firewall should be used by the service for permission checks of the operation. Otherwise, a username may be supplied that does not have webauthn and the point of the firewall is bypassed
   - This opens the case where the username is not what determines the permission on the service.
- Firewall in between the frontend and backend uses http. Firewall as the frontend should use https
- Firewall might need to configure proxy transport verify TLS certificate or not
- Some web-services want OPTIONS such as conduit, gogs for example does not
- Firewall identifier different between services, JWT, session, username directly, etc.
- Login does not work if it accepts email, but firewall does not store email, only username and userID
- Firewall `reqBody` JSON field names may need to be configurable.
- Incoming data may be JSON format of request body or form data
- Server-side rendering mainly uses URL begin since pre-load would also be an HTTP request, so no point to do so early and unnecessarily
